// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/jwt.service': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/jwt.service').default>>>>
    }
    '/api/auth/signin': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signin').default>>>>
    }
    '/api/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signup.post').default>>>>
    }
    '/api/auth/testToken': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/testToken').default>>>>
    }
    '/api/Authoriser_APi/Getreport_to_Authoriser': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Authoriser_APi/Getreport_to_Authoriser.get').default>>>>
    }
    '/api/Decision_Api/decision_admin_approved_rejected': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Decision_Api/decision_admin_approved_rejected.post').default>>>>
    }
    '/api/Decision_Api/decision_Appovestatus': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Decision_Api/decision_Appovestatus.get').default>>>>
    }
    '/api/Decision_Api/decision_Rejectedstatus': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Decision_Api/decision_Rejectedstatus.get').default>>>>
    }
    '/api/Decision_Api/decision_user_approve': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Decision_Api/decision_user_approve').default>>>>
    }
    '/api/Decision_Api/decision_verfier_approved_rejected': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Decision_Api/decision_verfier_approved_rejected.post').default>>>>
    }
    '/api/Decision_Api/decisionauthoriserapproved': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Decision_Api/decisionauthoriserapproved.post').default>>>>
    }
    '/api/Edit_vendor_APi/vendor': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Edit_vendor_APi/vendor.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Edit_vendor_APi/vendor.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Edit_vendor_APi/vendor.put').default>>>>
    }
    '/api/Edit_vendor_APi/vendordelete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Edit_vendor_APi/vendordelete.delete').default>>>>
    }
    '/api/fetchreport/fetchreportApproved_User': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fetchreport/fetchreportApproved_User').default>>>>
    }
    '/api/fetchreport/fetchreportauthoriser_approved': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fetchreport/fetchreportauthoriser_approved').default>>>>
    }
    '/api/fetchreport/fetchreportauthoriser_rejected': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fetchreport/fetchreportauthoriser_rejected').default>>>>
    }
    '/api/fetchreport/fetchreportRejected_User': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fetchreport/fetchreportRejected_User').default>>>>
    }
    '/api/fetchreport/fetchreportsforuser': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fetchreport/fetchreportsforuser').default>>>>
    }
    '/api/fetchreport/reqrechkforauth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fetchreport/reqrechkforauth').default>>>>
    }
    '/api/fetchreport/reqrechkforuser': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fetchreport/reqrechkforuser').default>>>>
    }
    '/api/fetchreport/reqrechkforverifier': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fetchreport/reqrechkforverifier').default>>>>
    }
    '/api/FetchRole/findadmin': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/FetchRole/findadmin.get').default>>>>
    }
    '/api/FetchRole/findauthoriser': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/FetchRole/findauthoriser.get').default>>>>
    }
    '/api/FetchRole/finduser': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/FetchRole/finduser.get').default>>>>
    }
    '/api/FetchRole/findVerifier': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/FetchRole/findVerifier.get').default>>>>
    }
    '/api/module1/BranchLocation/branchLocation': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/BranchLocation/branchLocation.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/BranchLocation/branchLocation.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/BranchLocation/branchLocation.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/BranchLocation/branchLocation.put').default>>>>
    }
    '/api/module1/Delete': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/Delete').default>>>>
    }
    '/api/module1/findUniq': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/findUniq').default>>>>
    }
    '/api/module1/GetNewPerson': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/GetNewPerson').default>>>>
    }
    '/api/module1/Update': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/Update').default>>>>
    }
    '/api/module1/UserAPI/addreport': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/UserAPI/addreport.post').default>>>>
    }
    '/api/module1/UserAPI/GetAllReports': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/UserAPI/GetAllReports').default>>>>
    }
    '/api/module1/vendor': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendor.post').default>>>>
    }
    '/api/module1/vendorCategoy_Api/vendorcategeorydata': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendorCategoy_Api/vendorcategeorydata').default>>>>
    }
    '/api/module1/vendorCategoy_Api/vendorcategoy': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendorCategoy_Api/vendorcategoy.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendorCategoy_Api/vendorcategoy.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendorCategoy_Api/vendorcategoy.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendorCategoy_Api/vendorcategoy.put').default>>>>
    }
    '/api/module1/vendorType_Api/vendorType': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendorType_Api/vendorType.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendorType_Api/vendorType.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendorType_Api/vendorType.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/module1/vendorType_Api/vendorType.put').default>>>>
    }
    '/api/newApi': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/newApi').default>>>>
    }
    '/api/recheck_Api/admin_to_verfier': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recheck_Api/admin_to_verfier.post').default>>>>
    }
    '/api/recheck_Api/fetch_report_rejected_verfier': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recheck_Api/fetch_report_rejected_verfier.post').default>>>>
    }
    '/api/recheck_Api/rejected_Api': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recheck_Api/rejected_Api.post').default>>>>
    }
    '/api/recheck_Api/rejetctedby_Verifier': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recheck_Api/rejetctedby_Verifier.post').default>>>>
    }
    '/api/recheck_Api/verifier_to_authoriser_Api': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recheck_Api/verifier_to_authoriser_Api.post').default>>>>
    }
    '/api/report_Api/addReport': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/report_Api/addReport').default>>>>
    }
    '/api/report_Api/report': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/report_Api/report.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/report_Api/report.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/report_Api/report.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/report_Api/report.put').default>>>>
    }
    '/api/report_Api/reportcreated': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/report_Api/reportcreated.post').default>>>>
    }
    '/api/signoutapi/signout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/signoutapi/signout').default>>>>
    }
    '/api/Verifier_Api/Getreport_to_admin': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Verifier_Api/Getreport_to_admin.get').default>>>>
    }
    '/api/Verifier_Api/Getreport_to_verfier': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/Verifier_Api/Getreport_to_verfier.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}